# Generated by Django 3.0.7 on 2020-11-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_fname', models.CharField(max_length=100)),
                ('C_lname', models.CharField(max_length=100)),
                ('C_username', models.CharField(max_length=100)),
                ('C_email', models.CharField(max_length=100)),
                ('C_password', models.CharField(max_length=100)),
                ('C_phone', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_picuture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_fname', models.CharField(max_length=100)),
                ('E_lname', models.CharField(max_length=100)),
                ('E_phone', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mypicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
