# Generated by Django 4.1.13 on 2026-10-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("img", models.FileField(upload_to="media/img", verbose_name="pic")),
                ("content", models.TextField(verbose_name="content")),
                ("c_time", models.DateTimeField(verbose_name="Date of create")),
            ],
        ),
    ]
